spring:
  application:
    name: codemx-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:codemx_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

evaluador:
  url: ${EVALUADOR_URL:http://localhost:8000}
